### ISSUE TITLE
Installation Issues

### ISSUE THREAD

**Issue by Jacquers** [mholo65/depends#10]
The tool package could not be restored.
Tool 'dotnet-depends' failed to install. This failure may have been caused by:

* You are attempting to install a preview release and did not use the --version option to specify the version.
* A package by this name was found, but it was not a .NET Core tool.
* The required NuGet feed cannot be accessed, perhaps because of an Internet connection problem.
* You mistyped the name of the tool.

**Comment by mholo65** [comment]
As per NuGet documentation (https://www.nuget.org/packages/dotnet-depends/), installation is done by:
```
dotnet tool install --global dotnet-depends --version 0.3.0
```

As global tools are framework dependent (https://docs.microsoft.com/en-us/dotnet/core/tools/global-tools#what-could-go-wrong), you need to have .NET Core 2.1 installed.

If problem persists, please open issue in [dotnet/cli](https://github.com/dotnet/cli) or [nuget/home](https://github.com/nuget/home) as these repos are better for tracking problems with installation of global tools.
