### ISSUE TITLE
The tool cannot be installed if no global nuget config is specified

### ISSUE THREAD

**Issue by snowinmars** [mholo65/depends#7]
**Requirements**
NuGet has [three configuration layers](https://docs.microsoft.com/ru-ru/nuget/consume-packages/configuring-nuget-behavior)

Remove all but solution configs.
Try to install the `depends` tool through `dotnet tool install`

**ER**
The tool installs successfully

**AR**
`error NU1101: Unable to find package dotnet-depends. No packages exist with this id in source(s): C:\Program Files\dotnet\sdk\NuGetFallbackFolder`

**How to fix**
Add the nuget source to the install command:

`dotnet tool install --global dotnet-depends --add-source 'https://api.nuget.org/v3/index.json'`

**Comment by mholo65** [comment]
This is a behaviour of NuGet and the problem you are seeing is with installation of global tools using `dotnet` cli. Please open issue in [dotnet/cli](https://github.com/dotnet/cli) or [nuget/home](https://github.com/nuget/home) as these repos are better for tracking problems with installation of global tools.
