### ISSUE TITLE
tool searches only for .csproj, other project file types need to specified explicitly

### ISSUE THREAD

**Issue by Ma3yTa** [mholo65/depends#8]
![image](https://user-images.githubusercontent.com/660379/62529075-24802c00-b868-11e9-9de5-d806efed7ca4.png)

**Comment by mholo65** [comment]
Sorry, cli searches explicitly for `.csproj` 

https://github.com/mholo65/depends/blob/df748370034b1858e711652e5304859bceb41dc5/src/Depends/Program.cs#L55

A workaround is to specify the path to your project file, e.g:
```
dotnet depends MyFunc.fsproj
```

I tested quickly, and it seems to work with F# projects as well. You would probably also encounter same issue with a VB.NET project as well.

**Comment by mholo65** [comment]
Fixed by 5a49e64e1c4fef477df22d5b56ec551df9d9df50
