### ISSUE TITLE
Shift Tab doesn't work.

### ISSUE THREAD

**Issue by rgelb** [mholo65/depends#9]
Tried it on both result command prompt and powershell. I can see that you are catching keys in CustomWindow.ProcessKey, but I am not sure how to tell gui.cs to go back.

**Comment by mholo65** [comment]
Thanks, I’ve noticed this also. I’ve already fixed it once in Gui.cs (https://github.com/migueldeicaza/gui.cs/pull/110). Need to check again, and see why it’s broken again.

**Comment by mholo65** [comment]
Should be fixed in https://github.com/migueldeicaza/gui.cs/pull/243
